import Foundation

/// Built-in exercise definitions sourced from exercise_export_tags_sides_final_20260710.csv.
enum DefaultExerciseCatalog {
    struct Entry: Hashable, Sendable {
        let name: String
        let groups: [MuscleGroup]
        let parentName: String?
        let laterality: ExerciseLaterality?

        init(
            name: String,
            groups: [MuscleGroup],
            parentName: String? = nil,
            laterality: ExerciseLaterality? = nil
        ) {
            self.name = name
            self.groups = groups
            self.parentName = parentName
            self.laterality = laterality
        }
    }

    static let entries: [Entry] = [
        .init(name: "45° Donkey Calf", groups: [.calves]),
        .init(name: "Ab Wheel", groups: [.core]),
        .init(name: "Arnold Press (Dumbbell)", groups: [.shoulders, .triceps]),
        .init(name: "Back Extension", groups: [.back, .glutes, .hamstrings]),
        .init(name: "Back Extension (Machine)", groups: [.back, .glutes, .hamstrings]),
        .init(name: "Bayesian Curl", groups: [.biceps]),
        .init(name: "Bayesian Curl - Left", groups: [.biceps], parentName: "Bayesian Curl", laterality: .left),
        .init(name: "Bayesian Curl - Right", groups: [.biceps], parentName: "Bayesian Curl", laterality: .right),
        .init(name: "Bench Press - Close Grip (Barbell)", groups: [.triceps, .chest, .shoulders]),
        .init(name: "Bench Press (Barbell)", groups: [.chest, .triceps, .shoulders]),
        .init(name: "Bent Over One Arm Row (Dumbbell)", groups: [.back, .biceps]),
        .init(name: "Bent Over One Arm Row (Dumbbell) - Left", groups: [.back, .biceps], parentName: "Bent Over One Arm Row (Dumbbell)", laterality: .left),
        .init(name: "Bent Over One Arm Row (Dumbbell) - Right", groups: [.back, .biceps], parentName: "Bent Over One Arm Row (Dumbbell)", laterality: .right),
        .init(name: "Bent Over Row (Dumbbell)", groups: [.back, .biceps]),
        .init(name: "Bicep Curl (Barbell)", groups: [.biceps]),
        .init(name: "Bicep Curl (Cable)", groups: [.biceps]),
        .init(name: "Bicep Curl (Dumbbell)", groups: [.biceps]),
        .init(name: "Bicep Curl (Machine)", groups: [.biceps]),
        .init(name: "Bicep Curl (Machine) (Bands)", groups: [.biceps]),
        .init(name: "Bulgarian Split Squat", groups: [.quads, .glutes]),
        .init(name: "Bulgarian Split Squat - Left", groups: [.quads, .glutes], parentName: "Bulgarian Split Squat", laterality: .left),
        .init(name: "Bulgarian Split Squat - Right", groups: [.quads, .glutes], parentName: "Bulgarian Split Squat", laterality: .right),
        .init(name: "Calf Extension Machine", groups: [.calves]),
        .init(name: "Calf Press on Seated Leg Press", groups: [.calves]),
        .init(name: "Chest Fly", groups: [.chest]),
        .init(name: "Chest Fly (Dumbbell)", groups: [.chest]),
        .init(name: "Chest Press (Machine)", groups: [.chest, .triceps, .shoulders]),
        .init(name: "Crucifix Crunches", groups: [.core]),
        .init(name: "Crunch", groups: [.core]),
        .init(name: "Crunch (Machine)", groups: [.core]),
        .init(name: "Cycling (Indoor)", groups: [.cardio]),
        .init(name: "Dead Hang", groups: [.forearms]),
        .init(name: "Deadlift (Smith Machine)", groups: [.hamstrings, .glutes, .back, .quads]),
        .init(name: "Elliptical Machine", groups: [.cardio]),
        .init(name: "EZ Bar Curl", groups: [.biceps]),
        .init(name: "Face Pull (Cable)", groups: [.back, .shoulders, .traps]),
        .init(name: "Flutter Kicks", groups: [.core, .hipFlexors]),
        .init(name: "Front Raise (Dumbbell)", groups: [.shoulders]),
        .init(name: "Glute Bridge (Dumbbell) - 20lb", groups: [.glutes]),
        .init(name: "Glute Kickback (Machine)", groups: [.glutes]),
        .init(name: "Glute Kickback (Machine) - Left", groups: [.glutes], parentName: "Glute Kickback (Machine)", laterality: .left),
        .init(name: "Glute Kickback (Machine) - Right", groups: [.glutes], parentName: "Glute Kickback (Machine)", laterality: .right),
        .init(name: "Goblet Squat (Kettlebell)", groups: [.quads, .glutes]),
        .init(name: "Hack Squat", groups: [.quads, .glutes]),
        .init(name: "Hollow Hold", groups: [.core]),
        .init(name: "Hammer Curl (Cable)", groups: [.biceps, .forearms]),
        .init(name: "Hammer Curl (Dumbbell)", groups: [.biceps, .forearms]),
        .init(name: "Hammer Curl (Dumbbell) - Left", groups: [.biceps, .forearms], parentName: "Hammer Curl (Dumbbell)", laterality: .left),
        .init(name: "Hammer Curl (Dumbbell) - Right", groups: [.biceps, .forearms], parentName: "Hammer Curl (Dumbbell)", laterality: .right),
        .init(name: "Hip Abductor (Cable)", groups: [.glutes]),
        .init(name: "Hip Abductor (Cable) - Left", groups: [.glutes], parentName: "Hip Abductor (Cable)", laterality: .left),
        .init(name: "Hip Abductor (Cable) - Right", groups: [.glutes], parentName: "Hip Abductor (Cable)", laterality: .right),
        .init(name: "Hip Abductor (Machine)", groups: [.glutes]),
        .init(name: "Hip Adductor (Cable)", groups: [.adductors]),
        .init(name: "Hip Adductor (Cable) - Left", groups: [.adductors], parentName: "Hip Adductor (Cable)", laterality: .left),
        .init(name: "Hip Adductor (Cable) - Right", groups: [.adductors], parentName: "Hip Adductor (Cable)", laterality: .right),
        .init(name: "Hip Adductor (Machine)", groups: [.adductors]),
        .init(name: "Hip Thrust (Bodyweight)", groups: [.glutes]),
        .init(name: "Hip Thrust Machine", groups: [.glutes]),
        .init(name: "Incline Bench Press (Barbell)", groups: [.chest, .shoulders, .triceps]),
        .init(name: "Incline Bench Press (Dumbbell)", groups: [.chest, .shoulders, .triceps]),
        .init(name: "Incline Bench Press (Smith Machine)", groups: [.chest, .shoulders, .triceps]),
        .init(name: "Incline Chest Press (Machine)", groups: [.chest, .shoulders, .triceps]),
        .init(name: "Incline Curl (Dumbbell)", groups: [.biceps]),
        .init(name: "Incline Curl (Dumbbell) - Left", groups: [.biceps], parentName: "Incline Curl (Dumbbell)", laterality: .left),
        .init(name: "Incline Curl (Dumbbell) - Right", groups: [.biceps], parentName: "Incline Curl (Dumbbell)", laterality: .right),
        .init(name: "Iso-Lateral Row (Machine)", groups: [.back, .biceps]),
        .init(name: "Knee Raise (Captain's Chair)", groups: [.core, .hipFlexors]),
        .init(name: "Lat Pulldown (Cable)", groups: [.back, .biceps]),
        .init(name: "Lat Pulldown (Machine)", groups: [.back, .biceps]),
        .init(name: "Lateral Raise (Cable)", groups: [.shoulders]),
        .init(name: "Lateral Raise (Cable) - Left", groups: [.shoulders], parentName: "Lateral Raise (Cable)", laterality: .left),
        .init(name: "Lateral Raise (Cable) - Right", groups: [.shoulders], parentName: "Lateral Raise (Cable)", laterality: .right),
        .init(name: "Lateral Raise (Dumbbell)", groups: [.shoulders]),
        .init(name: "Lateral Raise (Machine)", groups: [.shoulders]),
        .init(name: "Leg Extension (Machine)", groups: [.quads]),
        .init(name: "Leg Press", groups: [.quads, .glutes]),
        .init(name: "Low to High Cable Fly", groups: [.chest]),
        .init(name: "Lunge (Dumbbell)", groups: [.quads, .glutes]),
        .init(name: "Lunge (Dumbbell) - Left", groups: [.quads, .glutes], parentName: "Lunge (Dumbbell)", laterality: .left),
        .init(name: "Lunge (Dumbbell) - Right", groups: [.quads, .glutes], parentName: "Lunge (Dumbbell)", laterality: .right),
        .init(name: "Lunge (Kinesis Machine)", groups: [.quads, .glutes]),
        .init(name: "Lunge (Kinesis Machine) - Left", groups: [.quads, .glutes], parentName: "Lunge (Kinesis Machine)", laterality: .left),
        .init(name: "Lunge (Kinesis Machine) - Right", groups: [.quads, .glutes], parentName: "Lunge (Kinesis Machine)", laterality: .right),
        .init(name: "Lying Leg Curl (Machine)", groups: [.hamstrings]),
        .init(name: "Lying Leg Raise Hold", groups: [.core, .hipFlexors]),
        .init(name: "MTS Abdominal Crunch", groups: [.core]),
        .init(name: "MTS Row", groups: [.back, .biceps]),
        .init(name: "Overhead Press (Dumbbell)", groups: [.shoulders, .triceps]),
        .init(name: "Overhead Press (Machine)", groups: [.shoulders, .triceps]),
        .init(name: "Overhead Tricep Extensions (single arm, no attachment)", groups: [.triceps]),
        .init(
            name: "Overhead Tricep Extensions (single arm, no attachment) - Left",
            groups: [.triceps],
            parentName: "Overhead Tricep Extensions (single arm, no attachment)",
            laterality: .left
        ),
        .init(
            name: "Overhead Tricep Extensions (single arm, no attachment) - Right",
            groups: [.triceps],
            parentName: "Overhead Tricep Extensions (single arm, no attachment)",
            laterality: .right
        ),
        .init(name: "Overhead Tricep Extensions with Cable (low to high)", groups: [.triceps]),
        .init(name: "Plank", groups: [.core]),
        .init(name: "Preacher Curl (Barbell)", groups: [.biceps]),
        .init(name: "Preacher Curl (Dumbbell)", groups: [.biceps]),
        .init(name: "Preacher Curl (Dumbbell) - Left", groups: [.biceps], parentName: "Preacher Curl (Dumbbell)", laterality: .left),
        .init(name: "Preacher Curl (Dumbbell) - Right", groups: [.biceps], parentName: "Preacher Curl (Dumbbell)", laterality: .right),
        .init(name: "Preacher Curl (Machine)", groups: [.biceps]),
        .init(name: "Pull Up (Assisted)", groups: [.back, .biceps]),
        .init(name: "Push Up", groups: [.chest, .triceps, .shoulders]),
        .init(name: "RDL (Kettlebell)", groups: [.hamstrings, .glutes]),
        .init(name: "Reverse Crunch", groups: [.core]),
        .init(name: "Reverse Curl (Barbell)", groups: [.biceps, .forearms]),
        .init(name: "Reverse Curl (EZ Bar)", groups: [.biceps, .forearms]),
        .init(name: "Reverse Fly (Dumbbell)", groups: [.back, .shoulders, .traps]),
        .init(name: "Reverse Fly (Machine)", groups: [.back, .shoulders, .traps]),
        .init(name: "Reverse Plank", groups: [.core, .glutes, .hamstrings]),
        .init(name: "Romanian Deadlift (Dumbbell)", groups: [.hamstrings, .glutes]),
        .init(name: "Romanian Deadlift (Smith Machine)", groups: [.hamstrings, .glutes]),
        .init(name: "Rotary Torso Machine", groups: [.core]),
        .init(name: "Rotary Torso Machine - Left", groups: [.core], parentName: "Rotary Torso Machine", laterality: .left),
        .init(name: "Rotary Torso Machine - Right", groups: [.core], parentName: "Rotary Torso Machine", laterality: .right),
        .init(name: "Seated Calf Raise (Plate Loaded)", groups: [.calves]),
        .init(name: "Seated Leg Curl (Machine)", groups: [.hamstrings]),
        .init(name: "Seated Leg Press (Machine)", groups: [.quads, .glutes]),
        .init(name: "Seated Overhead Press (Dumbbell)", groups: [.shoulders, .triceps]),
        .init(name: "Seated Palms Down Wrist Curl (Dumbbell)", groups: [.forearms]),
        .init(name: "Seated Palms Up Wrist Curl (Dumbbell)", groups: [.forearms]),
        .init(name: "Seated Row (Cable)", groups: [.back, .biceps]),
        .init(name: "Seated Row (Machine)", groups: [.back, .biceps]),
        .init(name: "Shoulder Press (Machine)", groups: [.shoulders, .triceps]),
        .init(name: "Shrug (Barbell)", groups: [.traps]),
        .init(name: "Shrug (Dumbbell)", groups: [.traps]),
        .init(name: "Shrug (Smith Machine)", groups: [.traps]),
        .init(name: "Side Leg Raises", groups: [.glutes]),
        .init(name: "Side Leg Raises - Left", groups: [.glutes], parentName: "Side Leg Raises", laterality: .left),
        .init(name: "Side Leg Raises - Right", groups: [.glutes], parentName: "Side Leg Raises", laterality: .right),
        .init(name: "Side Plank Hip Raise (both sides)", groups: [.core]),
        .init(name: "Side Plank Hip Raise - Left", groups: [.core], parentName: "Side Plank Hip Raise (both sides)", laterality: .left),
        .init(name: "Side Plank Hip Raise - Right", groups: [.core], parentName: "Side Plank Hip Raise (both sides)", laterality: .right),
        .init(name: "Single Arm Tricep Extension (dumbbell)", groups: [.triceps]),
        .init(
            name: "Single Arm Tricep Extension (dumbbell) - Left",
            groups: [.triceps],
            parentName: "Single Arm Tricep Extension (dumbbell)",
            laterality: .left
        ),
        .init(
            name: "Single Arm Tricep Extension (dumbbell) - Right",
            groups: [.triceps],
            parentName: "Single Arm Tricep Extension (dumbbell)",
            laterality: .right
        ),
        .init(name: "Single Leg Leg Extension (Left)", groups: [.quads], parentName: "Leg Extension (Machine)", laterality: .left),
        .init(name: "Single Leg Leg Extension (Right)", groups: [.quads], parentName: "Leg Extension (Machine)", laterality: .right),
        .init(name: "Single Leg Seated Leg Curl (Left)", groups: [.hamstrings], parentName: "Seated Leg Curl (Machine)", laterality: .left),
        .init(name: "Single Leg Seated Leg Curl (Right)", groups: [.hamstrings], parentName: "Seated Leg Curl (Machine)", laterality: .right),
        .init(name: "Single-Arm Overhead Cable Extension", groups: [.triceps]),
        .init(name: "Single-Arm Overhead Cable Extension - Left", groups: [.triceps], parentName: "Single-Arm Overhead Cable Extension", laterality: .left),
        .init(name: "Single-Arm Overhead Cable Extension - Right", groups: [.triceps], parentName: "Single-Arm Overhead Cable Extension", laterality: .right),
        .init(name: "Single-Leg RDL", groups: [.hamstrings, .glutes]),
        .init(name: "Single-Leg RDL - Left", groups: [.hamstrings, .glutes], parentName: "Single-Leg RDL", laterality: .left),
        .init(name: "Single-Leg RDL - Right", groups: [.hamstrings, .glutes], parentName: "Single-Leg RDL", laterality: .right),
        .init(name: "Skullcrusher (Barbell)", groups: [.triceps]),
        .init(name: "Squat (Band)", groups: [.quads, .glutes]),
        .init(name: "Squat (Dumbbell)", groups: [.quads, .glutes]),
        .init(name: "Squat (Smith Machine)", groups: [.quads, .glutes]),
        .init(name: "Stair Stepper", groups: [.cardio]),
        .init(name: "Standing Calf Raise (Bodyweight)", groups: [.calves]),
        .init(name: "Standing Calf Raise (Dumbbell)", groups: [.calves]),
        .init(name: "Standing Calf Raise (Machine)", groups: [.calves]),
        .init(name: "Standing Calf Raise (Smith Machine)", groups: [.calves]),
        .init(name: "Straight Arm Pulldown", groups: [.back]),
        .init(name: "Superman", groups: [.back, .glutes, .hamstrings]),
        .init(name: "T Bar Row", groups: [.back, .biceps]),
        .init(name: "Tricep Overhead Extension With Rope", groups: [.triceps]),
        .init(name: "Triceps Dip", groups: [.triceps, .chest, .shoulders]),
        .init(name: "Triceps Dip (Assisted)", groups: [.triceps, .chest, .shoulders]),
        .init(name: "Triceps Extension (Dumbbell)", groups: [.triceps]),
        .init(name: "Triceps Extension (Machine)", groups: [.triceps]),
        .init(name: "Triceps Kickback (dumbbell)", groups: [.triceps]),
        .init(name: "Triceps Kickback (dumbbell) - Left", groups: [.triceps], parentName: "Triceps Kickback (dumbbell)", laterality: .left),
        .init(name: "Triceps Kickback (dumbbell) - Right", groups: [.triceps], parentName: "Triceps Kickback (dumbbell)", laterality: .right),
        .init(name: "Triceps Press Machine", groups: [.triceps]),
        .init(name: "Triceps Pushdown (Cable - Straight Bar)", groups: [.triceps]),
        .init(name: "Upright Row (Dumbbell)", groups: [.shoulders, .traps]),
        .init(name: "V-bar Pulldown", groups: [.back, .biceps]),
        .init(name: "Walking (Treadmill)", groups: [.cardio])
    ]

    static let relationships: [ExerciseRelationship] = entries.compactMap { entry in
        guard let parentName = entry.parentName, let laterality = entry.laterality else { return nil }
        return ExerciseRelationship(
            exerciseName: entry.name,
            parentName: parentName,
            laterality: laterality
        )
    }
}
