reporter: "xcode"

included:
  - workout-app

excluded:
  - workout-app.xcodeproj
  - workout-app/Assets.xcassets
  - workout-app/Preview Content
  - build
  - DerivedData
  - .build
  - Pods
  - Carthage
  - Packages

line_length:
  warning: 160
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 120
  error: 200

type_body_length:
  warning: 400
  error: 600

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - i
    - r
    - g
    - b
    - ok
    - x
    - y
    - z

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - contains_over_filter_count
  - sorted_first_last
  - redundant_nil_coalescing
  - trailing_newline
  - weak_delegate

analyzer_rules:
  - unused_import

disabled_rules:
  - force_cast
  - force_try
  - todo
  - vertical_whitespace_between_cases
